<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

// Snapshot of the live tickets table, captured for moving this project to the
// production server with its real data intact. Regenerate by re-running the
// generator script if the source data changes before the next migration.
class TicketSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('tickets')->insert([
            [
                'id' => '019fd5c9-5a3e-71e8-9cac-04194b6184fc',
                'ticket_number' => 'LGICT-26-1412',
                'users_id' => '019fd5c8-109b-7122-915e-498ee40f80ea',
                'assigned_to' => null,
                'ticket_type' => 'Medium',
                'request_category' => '—',
                'request_details' => null,
                'asset' => null,
                'subject' => 'Request adobe acrobat reinstallation',
                'concern' => 'User reported that she is unable to open her file using Adobe Acrobat.',
                'status' => 'Awaiting Supervisor',
                'escalation_level' => 0,
                'location' => '6th Floor - HQ',
                'started_at' => null,
                'resolved_at' => null,
                'created_at' => '2026-08-06 06:36:10',
                'updated_at' => '2026-08-06 06:36:39',
                'position' => 'Accounting Assistant',
                'business_unit' => 'CSS',
                'company' => 'Circle Corporate Inc.',
                'department' => 'Accounting Services',
                'level_request' => null,
                'employee_name' => null,
                'date_received' => '2026-08-03',
                'time_received' => '09:19:00',
                'date_acknowledged' => '2026-08-06',
                'time_acknowledged' => '06:36:16',
                'method' => 'Email',
                'sla_category_id' => '019fa69d-5ec5-73f7-80b5-c6060e9813ab',
                'subcategory_name' => 'Software Installation',
                'sla_due_at' => null,
                'sla_risk_notified_at' => null,
                'sla_breached_notified_at' => null,
                'response_time_minutes' => 15,
                'resolution_time_minutes' => 30,
                'cannot_resolve' => false,
                'cannot_resolve_findings' => null,
                'cannot_resolve_recommendation' => null,
                'workload_class_id' => '019fb21d-7356-71ec-bf63-5c973e527f90',
                'resolution_notes' => null,
                'service_type' => null,
                'findings' => null,
                'recommendation' => null,
                'resolved_by' => null,
                'scheduled_start' => null,
                'scheduled_end' => null,
                'is_overtime' => false,
                'queued_at' => null,
                'tech_acknowledged_at' => null,
                'validated_at' => null,
                'validation_notes' => null,
                'closed_at' => null,
            ],
            [
                'id' => '019fd5ce-50d9-70d4-a2a8-e94d65457bf9',
                'ticket_number' => 'LGICT-26-0002',
                'users_id' => 'ff9d92a0-371e-4c71-989c-7030775cac60',
                'assigned_to' => null,
                'ticket_type' => 'Medium',
                'request_category' => '—',
                'request_details' => 'Printer details: Brother Printer, Serial No. E77012E7F170714.',
                'asset' => null,
                'subject' => 'User reported that she is unable to print to the Brother printer at the Porac Site.',
                'concern' => 'Unable to print',
                'status' => 'Awaiting Supervisor',
                'escalation_level' => 0,
                'location' => 'Porac Site',
                'started_at' => null,
                'resolved_at' => null,
                'created_at' => '2026-08-06 06:41:35',
                'updated_at' => '2026-08-06 06:43:12',
                'position' => 'Leonio Group Employee',
                'business_unit' => 'No Assigned BU',
                'company' => 'No Assigned Company',
                'department' => 'No Assigned Department Name',
                'level_request' => null,
                'employee_name' => null,
                'date_received' => '2026-08-03',
                'time_received' => '09:03:00',
                'date_acknowledged' => '2026-08-06',
                'time_acknowledged' => '06:41:41',
                'method' => 'Microsoft Teams Chat',
                'sla_category_id' => '019fa69d-8650-72e3-9e16-2b9676b1ff10',
                'subcategory_name' => 'Internet Connectivity',
                'sla_due_at' => null,
                'sla_risk_notified_at' => null,
                'sla_breached_notified_at' => null,
                'response_time_minutes' => 30,
                'resolution_time_minutes' => 240,
                'cannot_resolve' => false,
                'cannot_resolve_findings' => null,
                'cannot_resolve_recommendation' => null,
                'workload_class_id' => '019fb21d-735b-73e2-ac86-3ae9cb66fce6',
                'resolution_notes' => null,
                'service_type' => null,
                'findings' => null,
                'recommendation' => null,
                'resolved_by' => null,
                'scheduled_start' => null,
                'scheduled_end' => null,
                'is_overtime' => false,
                'queued_at' => null,
                'tech_acknowledged_at' => null,
                'validated_at' => null,
                'validation_notes' => null,
                'closed_at' => null,
            ],
            [
                'id' => '019fd5d1-11c0-7273-a10d-cbfec8149384',
                'ticket_number' => 'LGICT-26-0003',
                'users_id' => 'a3116f42-bc1c-467b-bb04-1377610a3293',
                'assigned_to' => null,
                'ticket_type' => 'Low',
                'request_category' => '—',
                'request_details' => null,
                'asset' => null,
                'subject' => 'Request ERP License',
                'concern' => 'Transfer ERP License from Ms. Chatty to me',
                'status' => 'Awaiting Supervisor',
                'escalation_level' => 0,
                'location' => '6th Floor - HQ',
                'started_at' => null,
                'resolved_at' => null,
                'created_at' => '2026-08-06 06:44:36',
                'updated_at' => '2026-08-06 06:46:23',
                'position' => 'Leonio Group Employee',
                'business_unit' => 'No Assigned BU',
                'company' => 'No Assigned Company',
                'department' => 'No Assigned Department Name',
                'level_request' => null,
                'employee_name' => null,
                'date_received' => '2026-08-03',
                'time_received' => '10:14:00',
                'date_acknowledged' => '2026-08-06',
                'time_acknowledged' => '06:44:41',
                'method' => 'Microsoft Teams Chat',
                'sla_category_id' => '019fa69c-72a7-731f-9f12-1de2a91ebfb7',
                'subcategory_name' => 'Transfer ERP License',
                'sla_due_at' => null,
                'sla_risk_notified_at' => null,
                'sla_breached_notified_at' => null,
                'response_time_minutes' => 15,
                'resolution_time_minutes' => 30,
                'cannot_resolve' => false,
                'cannot_resolve_findings' => null,
                'cannot_resolve_recommendation' => null,
                'workload_class_id' => '019fb21d-7356-71ec-bf63-5c973e527f90',
                'resolution_notes' => null,
                'service_type' => null,
                'findings' => null,
                'recommendation' => null,
                'resolved_by' => null,
                'scheduled_start' => null,
                'scheduled_end' => null,
                'is_overtime' => false,
                'queued_at' => null,
                'tech_acknowledged_at' => null,
                'validated_at' => null,
                'validation_notes' => null,
                'closed_at' => null,
            ],
        ]);
    }
}
